language: java
sudo: false
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
jobs:
  include:
  - stage: Tests
    script: mvn clean test -B
  - stage: GitHub Release
    script: mvn clean verify -B -DskipTests 
    deploy:
      provider: releases
      api_key: $GITHUB_OAUTH_TOKEN 
      file: cucumber.eclipse.p2updatesite/target/*.zip
      skip_cleanup: true
      draft: true
      overwrite: true
      on:
        all_branches: true 
#        branch: master
    #    tags: true
