if: NOT tag =~ /^.*-.*$/ # Do not build prerelease tag 
language: java
sudo: false
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
jobs:
  include:
  - stage: Tests
    script: mvn clean test -B
  - stage: Deploy [pre]release on GitHub
    script: mvn clean verify -B -DskipTests
    before_deploy:
      - source ./continuous-deployment/prepare-deploy
    deploy:
      - provider: releases
        name: Snapshot branch $TRAVIS_BRANCH - $BUILD_DATE
        body: "$DESCRIPTION"
        prerelease: true
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true 
        file: cucumber.eclipse.p2updatesite/target/*.zip
        skip_cleanup: true
        overwrite: true
        on:
          all_branches: true
          tag: false
      - provider: releases
        name: Release $TRAVIS_TAG - $BUILD_DATE
        body: "$DESCRIPTION"
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true 
        file: cucumber.eclipse.p2updatesite/target/*.zip
        skip_cleanup: true
        on:
          tag: true
          condition: $TRAVIS_TAG != *"-"* # Do not redeploy prerelease
