language: java
sudo: false
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
jobs:
  include:
  - stage: Tests
    script: mvn test -B
  - stage: Create artifacts
    script: mvn package -B -DskipTests
  - stage: GitHub Release 
    deploy:
      provider: releases
      api_key:
        secret:
          secure: "$GITHUB_TOKEN_SECRET" 
      file: cucumber.eclipse.p2updatesite/target/*.zip
      skip_cleanup: true
      draft: true
      overwrite: true
    #  on:
    #    tags: true
