language: java
sudo: false
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
jobs:
  include:
  - stage: Tests
    script: mvn clean test -B
  - stage: GitHub Release
    script: mvn clean verify -B -DskipTests
    before_deploy:
      - export TRAVIS_TAG=${TRAVIS_TAG:-$(find ./cucumber.eclipse.p2updatesite/target -name "*.zip" | sed 's#.*cucumber-eclipse-plugin-\(.*\)\.zip#\1#')}
      - export GIT
#      - export RELEASE_TITLE="$TRAVIS_TAG $(date '+%Y-%m-%d %H:%M:%S') $TRAVIS_JOB_NUMBER"
    deploy:
      provider: releases
      name: Latest snapshot
      body: |
        Build [\#$TRAVIS_BUILD_NUMBER]($TRAVIS_BUILD_WEB_URL) of the latest snapshot from branch $TRAVIS_BRANCH, commit $TRAVIS_COMMIT.
      target: master
      api_key: $GITHUB_OAUTH_TOKEN
      file_glob: true 
      file: cucumber.eclipse.p2updatesite/target/*.zip
      skip_cleanup: true
      draft: true
      overwrite: true
      on:
        all_branches: true 
#        branch: master
    #    tags: true
