if: NOT tag # Do not build tag 
language: java
sudo: false
cache:
  directories:
  - "$HOME/.m2"
jdk:
- oraclejdk8
jobs:
  include:
  - stage: Tests
    script: mvn clean test -B
  - stage: Deploy [pre]release on GitHub
    script: mvn clean verify -B -DskipTests
    before_deploy:
      - ./continuous-deployment/prepare-deploy 
    deploy:
      - provider: releases
        name: Snapshot branch $TRAVIS_BRANCH - $BUILD_DATE
        prerelease: true
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true 
        file: cucumber.eclipse.p2updatesite/target/*.zip
        skip_cleanup: true
        overwrite: true
        on:
          all_branches: true 
      - provider: releases
        name: Release $TRAVIS_TAG - $BUILD_DATE
        api_key: $GITHUB_OAUTH_TOKEN
        file_glob: true 
        file: cucumber.eclipse.p2updatesite/target/*.zip
        skip_cleanup: true
        on: 
          condition: $TRAVIS_TAG != *"-"* # Do not redeploy prerelease
